name: Check for crypto and Format

on:
  pull_request:

jobs:
  check:
    name: Check for crypto
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for crypto
        uses: defi-wonderland/check-crypto-action@v1
        with:
          title: Check private key and notify
          branch: dev
          only_notify: true
          token: ${{ secrets.GITHUB_TOKEN }}

  format:
    name: Lint and Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '21.4'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install project dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm prettier

      - name: Run Linter
        run: pnpm lint
